pull_request_rules:
  - name: dispatch-on-pr
    conditions:
      - base=main
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: ci2.yml
              inputs:
                pr_title: "{{ title }}"
