pull_request_rules:
  - name: auto-update-as-maintainer
    conditions:
      - base = main
      - "#commits-behind > 0"
    actions:
      update:
        bot_account: uug4na
merge_protections_settings:
  reporting_method: check-runs
